### ISSUE TITLE
When I use 'def get_asf_session()' , it's wrong

### ISSUE THREAD

**Issue by ZGHHGZ** [ASFHyP3/hyp3-isce2#112] opened 2023-07-12 08:43 UTC
I found some bugs when I use "Local Python Package Interface"
########################################################################################
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
Code：
def get_asf_session() -> requests.Session:
session = requests.Session()
payload = {
'response_type': 'code',
'client_id': 'BO_n7nTIlMljdvU6kRRB3g',
'redirect_uri': 'https://auth.asf.alaska.edu/login',
}
response = session.get('https://urs.earthdata.nasa.gov/oauth/authorize',headers=headers, params=payload)
response.raise_for_status()
return session
########################################################################################
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
Error：
Traceback (most recent call last):
File "/home/zgh/anaconda3/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
httplib_response = self._make_request(
^^^^^^^^^^^^^^^^^^^
File "/home/zgh/anaconda3/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/connectionpool.py", line 449, in _make_request
six.raise_from(e, None)
File "", line 3, in raise_from
File "/home/zgh/anaconda3/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/connectionpool.py", line 444, in _make_request
httplib_response = conn.getresponse()
^^^^^^^^^^^^^^^^^^
File "/home/zgh/anaconda3/envs/hyp3-isce2/lib/python3.11/http/client.py", line 1378, in getresponse
response.begin()
File "/home/zgh/anaconda3/envs/hyp3-isce2/lib/python3.11/http/client.py", line 318, in begin
version, status, reason = self._read_status()
^^^^^^^^^^^^^^^^^^^
File "/home/zgh/anaconda3/envs/hyp3-isce2/lib/python3.11/http/client.py", line 287, in _read_status
raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/zgh/anaconda3/envs/hyp3-isce2/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
resp = conn.urlopen(
^^^^^^^^^^^^^
File "/home/zgh/anaconda3/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
retries = retries.increment(
^^^^^^^^^^^^^^^^^^
File "/home/zgh/anaconda3/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/util/retry.py", line 550, in increment
raise six.reraise(type(error), error, _stacktrace)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/zgh/anaconda3/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/packages/six.py", line 769, in reraise
raise value.with_traceback(tb)
File "/home/zgh/anaconda3/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
httplib_response = self._make_request(
^^^^^^^^^^^^^^^^^^^
File "/home/zgh/anaconda3/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/connectionpool.py", line 449, in _make_request
six.raise_from(e, None)
File "", line 3, in raise_from
File "/home/zgh/anaconda3/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/connectionpool.py", line 444, in _make_request
httplib_response = conn.getresponse()
^^^^^^^^^^^^^^^^^^
File "/home/zgh/anaconda3/envs/hyp3-isce2/lib/python3.11/http/client.py", line 1378, in getresponse
response.begin()
File "/home/zgh/anaconda3/envs/hyp3-isce2/lib/python3.11/http/client.py", line 318, in begin
version, status, reason = self._read_status()
^^^^^^^^^^^^^^^^^^^
File "/home/zgh/anaconda3/envs/hyp3-isce2/lib/python3.11/http/client.py", line 287, in _read_status
raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/mnt/c/Users/23361/Desktop/hyp3-isce2-develop/src/hyp3_isce2/etc/download_example.py", line 21, in
with get_asf_session() as session:
^^^^^^^^^^^^^^^^^
File "/home/zgh/hyp3-isce2/src/hyp3_isce2/burst.py", line 292, in get_asf_session

File "/home/zgh/anaconda3/envs/hyp3-isce2/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
return self.request("GET", url, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/zgh/anaconda3/envs/hyp3-isce2/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
resp = self.send(prep, **send_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/zgh/anaconda3/envs/hyp3-isce2/lib/python3.11/site-packages/requests/sessions.py", line 725, in send
history = [resp for resp in gen]
^^^^^^^^^^^^^^^^^^^^^^
File "/home/zgh/anaconda3/envs/hyp3-isce2/lib/python3.11/site-packages/requests/sessions.py", line 725, in
history = [resp for resp in gen]
^^^^^^^^^^^^^^^^^^^^^^
File "/home/zgh/anaconda3/envs/hyp3-isce2/lib/python3.11/site-packages/requests/sessions.py", line 266, in resolve_redirects
resp = self.send(
^^^^^^^^^^
File "/home/zgh/anaconda3/envs/hyp3-isce2/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
r = adapter.send(request, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/zgh/anaconda3/envs/hyp3-isce2/lib/python3.11/site-packages/requests/adapters.py", line 501, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
ERROR conda.cli.main_run:execute(47): conda run python /mnt/c/Users/23361/Desktop/hyp3-isce2-develop/src/hyp3_isce2/etc/download_example.py failed. (See above for error)

**Comment by jtherrmann** [comment] 2023-07-26 22:04
Hi @ZGHHGZ, can you please provide the command that you're attempting to run?

**Comment by jtherrmann** [comment] 2023-07-26 22:11
Closing this as a duplicate of https://github.com/ASFHyP3/tutorials/issues/8

**Closed by jtherrmann** 2023-07-26 22:11 UTC
Labels: bug
